[package]
name = "minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
litex-openfpga = { path = "../../crates/litex-openfpga" }

embedded-alloc = "0.5.0"
embedded-hal = "0.2.7"
riscv = { version = "0.10.1", features = ["critical-section-single-hart"] }
riscv-rt = "0.11.0"