fps:
	cd examples/rough_fps && \
	cargo build --release && \
	cargo objcopy --release -- -O binary ../../rust.bin

rtc:
	cd examples/rtc_id && \
	cargo build --release && \
	cargo objcopy --release -- -O binary ../../rust.bin

vblank:
	cd examples/vblank && \
	cargo build --release && \
	cargo objcopy --release -- -O binary ../../rust.bin