export component AudioUI {
  Image {
    y: 0;
    x: 60px;
    source: @image-url("RickAstley.png");
  }
  Rectangle {
    x: 0;
    y: 0;
    width: 267px;
    height: 1px;
    background: blue;
  }
  Rectangle {
    x: 0;
    y: 239px;
    width: 267px;
    height: 1px;
    background: blue;
  }
  Rectangle {
    x: 0;
    y: 0;
    width: 1px;
    height: 240px;
    background: red;
  }
  Rectangle {
    x: 266px;
    y: 0;
    width: 1px;
    height: 240px;
    background: red;
  }
}